version: '3.8'

services:
  fastapi:
    build: .
    command: uvicorn main_celery:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - BROKER_URL=redis://redis:6379/0

  celery:
    build: .
    command: celery -A main_celery.celery_app worker --loglevel=info

    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - BROKER_URL=redis://redis:6379/0

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
