version: '3.8'

services:
  fastapi:
    build: .
    command: uvicorn main_celery:app --host 0.0.0.0 --port 7000 --reload
    volumes:
      - .:/app
    ports:
      - "7000:7000"
    depends_on:
      - redis
    environment:
      - BROKER_URL=redis://red-csqt4bd2ng1s73bptkkg:6379

  celery:
    build: .
    command: celery -A main_celery.celery_app worker --loglevel=info

    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - BROKER_URL=redis://red-csqt4bd2ng1s73bptkkg:6379

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
